server:
  port: 8088


spring:
  application:
    name: auth-service

  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/ierp-springcloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    password: